name = "crove-email-inbound-worker"
main = "src/index.ts"
compatibility_date = "2024-11-05"
account_id = "5f2a58925e790423dfafa0e6bee46b28"

[vars]
DESK_WEBHOOK_URL = "https://desk.crove.com/api/third/email/webhook"
DESK_WEBHOOK_SECRET = "crove_email_secret_token_123"
